### ISSUE TITLE
Didn't know where else to put this. Muffler Saved Data?

### ISSUE THREAD

**Issue by PeaceIsBliss** [MorningSage/ExtremeSoundMuffler-Fabric#8]
"The list of muffled sounds are stored in the profile folder, so you don't need to re-muffle the sounds on every world."

On multiplayer hosted servers, should I assume this data is on server side? I can not for the life of me find a local file.

**Comment by funnyboy-roks** [comment]
AFAIK, there should be a folder in the root of your Minecraft directory called `ESM` that should contain the files related to the mod

**Comment by PeaceIsBliss** [comment]
Wow, there it is, after all this searching! Feel very foolish. Also something I noticed, that folder does NOT exist until you load the game at least once.

Thank you very much.

**Comment by funnyboy-roks** [comment]
Yes, the folder does not exist until the mod creates it, which can only happen after the game is run.
